---
- name: Provisioning lab infrastructure services and VMs
  hosts: hypervisor
  remote_user: "{{ admin_user }}"
  vars_files:
    - vars/infrastructure.yml
  roles:
    # Install virtualbox
    - role: yasarlaro.virtualbox
      become: yes

    # Install vagrant
    - role: yasarlaro.vagrant
      become: yes

    # Provision Jenkins VM
    - role: yasarlaro.vagrant-provisioner
      remote_user: "{{ admin_user }}"
      vars:
        box_name: "generic/centos7"
        box_hostname: jenkins.onur.lab
        box_memory: 4096
        box_cpu: 2
        box_ip: 192.168.0.51
        box_directory: "/home/onur/vagrant/{{ box_hostname }}"

# Installation of infrastructure servers play
- name: Installation of infrastructure services play
  hosts: all
  remote_user: vagrant
  become: yes
  roles:
    - role: yasarlaro.jenkins
      when: inventory_hostname in groups["lab-jenkins"]
