---
# tasks file for yasarlaro.jenkins-vagrant
- name: Create jenkins vagrant directory
  file:
    path: "{{ jenkins_dir }}"
    state: directory
    recurse: true
    owner: "{{ admin_user }}"
    group: "{{ admin_group }}"
    mode: 0755

- name: Deploy Vagrant file
  template:
    src: jenkins_vagrant.j2
    dest: "{{ jenkins_dir }}/Vagrantfile"
    owner: onur
    group: onur
    mode: 0644

- name: Create Jenkins VM
  shell: vagrant up
  args:
    chdir: "{{ jenkins_dir }}"

- name: "Allow {{ jenkins_forward_port }} on host server"
  firewalld:
    port: "{{ jenkins_forward_port }}/tcp"
    permanent: yes
    state: enabled
  become: yes