---
# Tasks for installing jenkins vm
- name: Create main and shared directory or Jenkins VM
  file:
    path: "{{ jenkins_shared_dir }}"
    state: directory
    mode: 0755
    owner: onur
    group: onur

- name: Deploy Vagrant file
  template:
    src: jenkins_vagrant.j2
    dest: "{{ jenkins_dir }}/Vagrantfile"
    owner: onur
    group: onur
    mode: 0644

- name: Deploy jenkins init script
  copy:
    src: jenkins_info.sh
    dest: "{{ jenkins_shared_dir }}/jenkins_info.sh"
    owner: onur
    group: onur
    mode: 0755

- name: Create Jenkins VM
  shell: vagrant up
  args:
    chdir: "{{ jenkins_dir }}"
